<script setup lang="ts">
import type { SummaryItem } from '~/types/codeatlas'

defineProps<{
  summaryItems: SummaryItem[]
  answer: string
}>()

const toneClass: Record<SummaryItem['tone'], string> = {
  neutral: 'text-atlas-info',
  good: 'text-atlas-success',
  risk: 'text-atlas-danger',
  opportunity: 'text-atlas-accent'
}
</script>

<template>
  <section class="atlas-panel flex h-full flex-col">
    <div class="flex items-center justify-between border-b border-atlas-line px-4 py-3">
      <h2 class="ui-title text-base">AI summary</h2>
      <button type="button" class="ui-button h-8 border-atlas-border bg-white px-3 text-xs text-atlas-muted hover:text-atlas-ink">
        <span class="ui-span">Copy</span>
      </button>
    </div>
    <div class="flex flex-1 flex-col gap-4 px-4 py-4">
      <p class="text-sm leading-6 text-atlas-ink">
        {{ answer }}
      </p>
      <div class="space-y-3">
        <div v-for="item in summaryItems" :key="item.label" class="flex gap-3">
          <span class="ui-span mt-1 grid h-5 w-5 shrink-0 place-items-center rounded border border-current/25 text-xs font-bold" :class="toneClass[item.tone]">
            -
          </span>
          <p class="text-sm leading-5 text-atlas-muted">
            <strong class="font-semibold text-atlas-ink">{{ item.label }}:</strong>
            {{ item.text }}
          </p>
        </div>
      </div>
      <div class="mt-auto flex items-center justify-between pt-2 text-xs text-atlas-muted">
        <span class="ui-span">Generated by CodeAtlas AI</span>
        <div class="flex gap-2">
          <button type="button" class="ui-button h-8 w-8 border-atlas-border bg-white text-atlas-muted hover:text-atlas-accent" aria-label="Mark useful">
            <span class="ui-span">+</span>
          </button>
          <button type="button" class="ui-button h-8 w-8 border-atlas-border bg-white text-atlas-muted hover:text-atlas-danger" aria-label="Mark not useful">
            <span class="ui-span">-</span>
          </button>
        </div>
      </div>
    </div>
  </section>
</template>
